server:
  port: 8088

spring:
  application:
    name:  dbmanage #服务名
  profiles:
    active: default # 配置文件的版本
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validateMigrationNaming: false
    createSchemas: false
    #initSql: CREATE IF NOT EXISTS flyway_history_schema
    url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    schemas: world
    user: root
    password: 1234
